### ISSUE TITLE
[FEATURE REQUEST] Implement Remote Config REST API

### ISSUE THREAD

**Issue by BearDooks** [GodotNuts/GodotFirebase#106]
https://firebase.google.com/docs/reference/remote-config/rest

**Comment by BearDooks** [comment]
Closing this for now

**Comment by WolfgangSenff** [comment]
I'm reopening this as we finally have someone requesting it other than myself. :)

**Comment by WolfgangSenff** [comment]
Okay, figured out why we couldn't do it! Closed again because it uses gRPC and we cannot (easily) support that in a REST service.
