### ISSUE TITLE
Get Data from existing realtime database object

### ISSUE THREAD

**Issue by Zarasan** [GodotNuts/GodotFirebase#114]
I have a realtime database set up and I am trying to get data from it. I could only find new_data_update and patch_data_update signals, how do I get existing data?

**Comment by WolfgangSenff** [comment]
It should be in the new_data_updated signal.

**Comment by Zarasan** [comment]
var fstore
fstore = Firebase.Database.get_database_reference('Users/01ojEi6zjaNR82CxvBc0Zfvt9pa2', {})
fstore.connect("new_data_update", self, "on_received_new_chat")

and I never get a signal with the data that is there in the database, am I doing something wrong? Should I call get() like in firestore?

**Comment by BearDooks** [comment]
@Zarasan when new data is added, can you see it in the console at that path?

Are you sure the path you have connected to is correct?

**Comment by WolfgangSenff** [comment]
Can I see the definition of the `on_received_new_chat` function?

**Comment by Zarasan** [comment]
@BearDooks I don't need to wait for new data like in the chat example, I have user information already defined there and I need to access it

@WolfgangSenff its just a simple print(data) function

**Comment by Zarasan** [comment]
This problem was on my end. Sorry for disturbing you.
Thank you so much for helping

**Comment by WolfgangSenff** [comment]
It's cool - it's what we're here for. :) Good luck!

**Comment by WolfgangSenff** [comment]
@Zarasan - by the way, I recently fixed a dumb bug with the authorization stuff. The fix is already in latest, but if you're using the branch from the Godot Asset Library, you likely won't have it. It's an easy fix though and since it's the latest thing to be merged, very easy to see what you have to do for the fix.
