### ISSUE TITLE
[BUG] Dictionaries inside Arrays from Firestore not parsed correctly

### ISSUE THREAD

**Issue by timjrobinson** [GodotNuts/GodotFirebase#131]
**Describe the bug**
When retrieving data from a Firestore document that contains an array with dictionaries inside it, the dictionaries are not being parsed. 

**To Reproduce**
Create a Firestore Collection
Inside the collection create a document that contains an array
Add an item to the array with key `0` and data of `{"name": "someone"}` with GodotFirebase
Retrieve the document using GodotFirebase `collection.get()`.
The document will have the contents:

`{"players":[{"fields":{"name":{"stringValue":"someone"}}}]}`

**Expected behavior**
I expect nested arrays/dictionaries to parse correctly to remove the `fields` property and `stringValue` and Firestore properties. The data returned from `collection.get` should look like:

`{"players": [{"name": "someone"}]}`

**Screenshots**

Debugging in Godot, this is the value of the document returned via `collection.get()`:

![2021-02-16 17_40_12-Godot Engine - CodeBreaker - ClientGame tscn](https://user-images.githubusercontent.com/525534/108035949-52f8dd00-7083-11eb-81f7-1561de9cb2e6.png)

How it looks in Firebase console:

![2021-02-16 18_21_33-Puzzop Games – Cloud Firestore – Firebase console](https://user-images.githubusercontent.com/525534/108036342-d1557f00-7083-11eb-8e30-61b9427b50f4.png)

**Environment:**
 - OS: Windows 10

**Additional Information**

It would be good to include unit tests for this too, as this regression has come up before. I fixed it in #80 and it's now reappeared since the refactor.

**Comment by WolfgangSenff** [comment]
@fenix-hub - sounds like the refactor slightly broke parsing. Any chance you'll be able to look at this this week?

**Comment by fenix-hub** [comment]
Yep, I'll give it a look for sure.
