### ISSUE TITLE
[BUG] Testing page in wiki mentions plugin directory that no longer exists

### ISSUE THREAD

**Issue by timjrobinson** [GodotNuts/GodotFirebase#133]
**Describe the bug**
On the testing page: https://github.com/GodotNuts/GodotFirebase/wiki/Testing it mentions to cd into a `plugin` directory and also that tests live inside `plugin/tests/...`. This directory no longer exists so should be removed from this wiki page.

**Comment by BearDooks** [comment]
Awesome catch. Thank you @timjrobinson 

I have updated the wiki to reflect changes

**Comment by timjrobinson** [comment]
Under the "Creating Tests" section it still says they live in the `plugin` directory.

**Comment by BearDooks** [comment]
@timjrobinson you are correct. I just removed those as well. Let me know if I missed anything else.

Thanks

Chuck
