### ISSUE TITLE
Can't use Google login in android app

### ISSUE THREAD

**Issue by spyr0s** [GodotNuts/GodotFirebase#170]
**Describe the bug**
Google login works fine when used in a  desktop app (f.e in Godot play project button) but when deployed on android I'm getting 
`Firebase Auth is currently busy and cannot process this request` errors

**To Reproduce**
Implement Firebase Google Auth as described in the docs
Use Play Project button in godot 
Google log in works as expected
Use deploy in android button in Godot
Press Sign in with google button in the app
Browser opens and let's you select the google account you want to sign in with
You are taken to the code page where you copy the code  
You paste the code in the app lineedit
you call Firebase.Auth.login_with_oauth(new_text)
You're getting many `Firebase Auth is currently busy and cannot process this request` until the outup is overflowed

**Expected behavior**
Google sign in should work as in desktop app

**Environment:**
 - OS: Android (Using mac OS for godot)
 
**Additional context**

**Comment by spyr0s** [comment]
After some debugging I see that I got this response from  exchange_google_token

`{
  "error": "invalid_grant",
  "error_description": "Malformed auth code."
}`

I am not sure why

**Comment by BearDooks** [comment]
@spyr0s thanks for bringing this to our attention. @fenix-hub and I are currently looking into it.

**Comment by spyr0s** [comment]
I think it's not your bug.
I found out that LineEdit on android does not return the whole code on the text_change event
Instead of returning 
`4/1AY0e-g6mWzoSsttJlwtTLWgl8YOgbIiJEJEZtlfS9....`
it returns just
`4` 
Maybe there's a bug with the / character.
I'm looking into this

**Comment by BearDooks** [comment]
@spyr0s good to know and awesome job finding it. I will talk with the team and see what we can do.

**Comment by fenix-hub** [comment]
@spyr0s Thanks for checking this out! Actually looks something that needs to be issued on Godot's repository itself.
