### ISSUE TITLE
[BUG] firestore emits non existing signales

### ISSUE THREAD

**Issue by ReneHabermann** [GodotNuts/GodotFirebase#181]
**Describe the bug**
firestore.gd contains several emissions of a signal that doesn't exist, "task_error". (:348, :352, :356, ..)
emit_signal("task_error", code, status, message)

**To Reproduce**
Acces a document in firestore that provokes an error, like insufficient permissions.

**Expected behavior**
error signals should be declared to be signalled

**Comment by WolfgangSenff** [comment]
What version are you using? The latest from here, or the latest from the Asset Library?

**Comment by ReneHabermann** [comment]
Latest from here, on main.
https://github.com/GodotNuts/GodotFirebase/blob/main/addons/godot-firebase/firestore/firestore.gd

There is no signal "task_error" in this class, but the signal emission is done, for example in line 348.

**Comment by WolfgangSenff** [comment]
Closed by #183.
