### ISSUE TITLE
[BUG] Firebase Timestamp

### ISSUE THREAD

**Issue by Zarasan** [GodotNuts/GodotFirebase#195]
**Describe the bug**
Firestore Timestamp doesn't have weekday and dst keys, which cause error when you have an array of timestamps from Firebase and you try to send them back it gives error

**To Reproduce**
Get a timestamp from firestore, try to send it back to firestore

**Expected behavior**
Should remove check if timestamp has dst and weekday and then remove them

**Environment:**
 - OS: Windows 10

**Additional context**
My local solution:
![image](https://user-images.githubusercontent.com/43384612/119329544-a0d64000-bc85-11eb-9b98-808ecbfd3328.png)

**Comment by WolfgangSenff** [comment]
Thanks for the PR!
