### ISSUE TITLE
[BUG] Firestore List Empty Collection

### ISSUE THREAD

**Issue by Zarasan** [GodotNuts/GodotFirebase#197]
**Describe the bug**
I get an error when I list empty collections

**To Reproduce**
List an empty collection in firebase using .list command

**Expected behavior**
It should give empty array

**Screenshots**
It says there are no documents in bod

**Environment:**
 - OS: Windows 10

**Additional context**
My fix:
![image](https://user-images.githubusercontent.com/43384612/119344911-88bbec00-bc98-11eb-8417-9cacb9adb8be.png)

**Comment by WolfgangSenff** [comment]
Thanks for the PR!
