### ISSUE TITLE
[BUG]Request Query gives unformatted documents

### ISSUE THREAD

**Issue by Zarasan** [GodotNuts/GodotFirebase#199]
**Describe the bug**
Query gives unformatted documents

**To Reproduce**
Query a document

**Expected behavior**
It should give formatted Firebase Documents

**Environment:**
 - OS: Windows 10

**Additional context**
My fix:
![image](https://user-images.githubusercontent.com/43384612/119365592-5c13ce80-bcb0-11eb-8db4-98d124879810.png)

**Comment by WolfgangSenff** [comment]
Hm. So this is now returning an array instead of the document directly?

**Comment by Zarasan** [comment]
document:{createTime:2021-05-24T13:47:36.525224Z, fields:{CountryCode:{stringValue:33}, FirstName:{stringValue:Aaron}, LastName:{stringValue:Asmith}, Mail:{stringValue:user1@qwerty.com}, MoodRequested:{booleanValue:False}, Organization:{stringValue:QWERTY}, PhoneNumber:{stringValue:123}, Points:{integerValue:20}, Role:{stringValue:User}}, name:'redacted', updateTime:2021-05-24T14:38:03.251779Z}, readTime:2021-05-24T18:36:06.858684Z}

**Comment by WolfgangSenff** [comment]
Okay. I'm a little worried this could break backward compatibility, if people are using it and not expecting an array like that to come back, but instead a dictionary. Let me confer with the team to make sure I'm not missing something.

**Comment by Zarasan** [comment]
You can close this its no problem I just share what I have encountered

**Comment by WolfgangSenff** [comment]
Oh, it's probably good and I'm probably just missing stuff! I'd rather have the code if people are running into issues with it, and you are good people. :)
