### ISSUE TITLE
New manual google auth function not exchanging successfully

### ISSUE THREAD

**Issue by macktns** [GodotNuts/GodotFirebase#210]
**Describe the bug**
The new get_google_auth_manual does not work in my project and no errors are shown. Replacing auth.gd with a previous version works when calling get_google_auth.

**To Reproduce**
I created a brand new project and installed the current version of this plugin. I use Firebase.Auth.get_google_auth_manual() which redirects me to the browser okay. I then call Firebase.Auth.login_with_oauth(oath_token) and nothing happens. This happens because the token is not being exchanged successfully. _exchange_google_token comes back false so the request is never made. 

**Expected behavior**
Replacing auth.gd with a version that has  the original get_google_auth allows me to login without problem. 

**Environment:**
 - OS: Windows 10
 - Browser chrome

**Additional context**
I do not have measurementId or domainUriPrefix setup, but I don't think that matters.

**Comment by WolfgangSenff** [comment]
I believe the workflow changed for that particular path. See here for a discussion that may help: https://github.com/GodotNuts/GodotFirebase/issues/207#issuecomment-864102021 I'll leave this open in case there's any other issue after you've finished, but I think the above might fix it for you. There's also some more info in #205 .

**Comment by macktns** [comment]
The function I would like to use is Get_google_auth_manual which is just a renamed version of get_google_auth. I don't think the work flow has changed for that function but I could be wrong. The new workflows and the linked discussions are for the new  get_google_auth_redirect and get_google_auth_localhost. I still prefer the manual copy paste because being automatically redirected to an error page with localhost is confusing for someone that doesn't know what happened in the background.

**Comment by fenix-hub** [comment]
@macktns Hi,
Now you should be able to use the manual function back again.
The automatic method changed the `exchange` function a little bit, so the process stopped just right there as you noticed.
Now you should be able to use the combination again
```gdscript
Firebase.Auth.get_google_auth_localhost()
Firebase.Auth.login_with_oauth(token)
```

**Comment by macktns** [comment]
Thank you!!
