### ISSUE TITLE
[FEATURE REQUEST] Implement Firebase Cloud Functions API

### ISSUE THREAD

**Issue by itsarjunsinh** [GodotNuts/GodotFirebase#213]
Hello! Thanks for this much-needed project. It's great!

**Is your feature request related to a problem? Please describe.**
To use cloud functions, Godot projects need to write helpers to make http calls with specific headers and auth tokens. Ideally it should be in the Firebase client sdk.

**Describe the solution you'd like**
Provide API to call Firebase Cloud functions like [official Firebase client sdks](https://firebase.google.com/docs/functions/callable#call_the_function).

**Additional context**
[Firebase Docs: Callable functions (client)](https://firebase.google.com/docs/functions/callable)
[Firebase Docs: Protocol specification for https.onCall](https://firebase.google.com/docs/functions/callable-reference)
[Classes/approach in client sdk for Flutter](https://pub.dev/documentation/cloud_functions/latest/cloud_functions/cloud_functions-library.html)

**Comment by WolfgangSenff** [comment]
Oh! That's actually a relatively new API, didn't know it existed. I'll look into it and likely implement it myself. Thanks!

**Comment by WolfgangSenff** [comment]
While I implement this, by the way, you know you can have these be called indirectly through changes in the database and Firestore (and almost everything), right? Just want to make sure you're not blocked, @itsarjunsinh.

**Comment by itsarjunsinh** [comment]
It didn't occur to me. It is a pretty clever short-term solution. Thanks.

**Comment by WolfgangSenff** [comment]
It's actually the original way to handle it - Functions originally weren't able to be called directly. :P You could only trigger them via changes to things, because of how they're built in node.
