### ISSUE TITLE
[BUG] `login_failed` signal emitted when `signup_with_email_and_password` request fails

### ISSUE THREAD

**Issue by lokimckay** [GodotNuts/GodotFirebase#219]
**Describe the bug**
As per the Wiki
( https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management#signup-with-email )

The `signup_with_email_and_password` method emits a `login_failed` signal when the signup attempt is unsuccessful

**Impact**
This is problematic when trying to display feedback messages to the user  
There is no way to differentiate between a signup failure message and a login failure message  

This means that in an application where it is possible to switch between Login and Signup pages while a request is still in flight, it is possible for a user to see a mismatched error message about a failed login attempt on the Signup page

**To Reproduce**
1. Configure the plugin as per Activation and Installation steps in the Wiki
1. Make the following call: `Firebase.Auth.signup_with_email_and_password("nonexistant@email.com", "fakepass")`
1. Observe that "login_failed" signal is emitted

**Expected behavior**
- A `signup_failed` signal should be emitted
- It should be possible to differentiate between a failed login request and a failed signup request

**Screenshots**
N/A

**Environment:**
 - OS: Windows 10

**Additional context**
Switching to a `signup_failed` signal would better match the existing `signup_succeeded` signal that is emitted when the call is successful

Relevant source code section:
https://github.com/GodotNuts/GodotFirebase/blob/main/addons/godot-firebase/auth/auth.gd#L300

**Comment by WolfgangSenff** [comment]
Hm. This is a good idea and shouldn't be too hard. I'll implement it when I have some time. Thanks for the bug!

**Comment by BearDooks** [comment]
@lokimckay We are currently working on this request and hope to have it put into the plugin soon. Thanks again for the suggestion.

Chuck
