### ISSUE TITLE
[BUG] Error Code 3 while adding document

### ISSUE THREAD

**Issue by ArtistSaihaan** [GodotNuts/GodotFirebase#220]
I was just experimenting with this plugin/addon. But when I tried to add document for the first time it worked. But for the second time it didnt. It gave error code of 3 and error was:
invalid get index error {on base: disctionary}

I wrote:
Collection.add(DocumentName, {fields})

While in wiki:
var add_task : FirestoreTask = firestore_collection.add("DOCUMENT_ID", {'name': 'Document Name', 'active': 'true'})
var document : FirestoreDocument = yield(add_task, "task_finished")

So is that causing problems

**Comment by BearDooks** [comment]
@ArtistSaihaan Can you share the code you are using to add a document

In the tester app we use, I have something like this written 

```
# Connect to the collection
	_collection = Firebase.Firestore.collection('Firebasetester')

# Connect needed signals for testing
	_collection.connect("add_document", self, "on_document_add")
	_collection.connect("get_document", self, "on_document_get")
	_collection.connect("update_document", self, "on_document_update")
	_collection.connect("delete_document", self, "on_document_delete")
	_collection.connect("error", self, "on_document_error")

# Add Document
	var add_task : FirestoreTask = _collection.add("Document2", {'name': 'Document2', 'active': 'true'})

# Update Document 2
	var up_task : FirestoreTask = _collection.update("Document2", {'name': 'Document2', 'active': 'true', 'updated' : 'true'})
```

I also have some error functions that print out what went wrong if you need me to share those. You can also find them here
https://github.com/GodotNuts/GodotFirebase/wiki/Firestore#firestoretask

Thanks

Chuck

**Comment by ArtistSaihaan** [comment]
Hero BearDooks/Chuck I am sharing you the code:
extends Node2D


# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass


func _on_SignUp_pressed():
	get_tree().change_scene("res://SignUp.tscn")
	pass # Replace with function body.


func _on_Login_pressed():
	get_tree().change_scene("res://Login.tscn")
	pass # Replace with function body.


func _on_Databaazi_pressed():
	get_tree().change_scene("res://DataStorage.tscn")
	pass # Replace with function body.

**Comment by BearDooks** [comment]
OK. By chance is the document name the same as the first one, or does it start with a number?

Where is the data being fed from?

Everything else looks correct to me.

Chuck

**Comment by ArtistSaihaan** [comment]
Nope everything is correct but then also its happening

**Comment by ArtistSaihaan** [comment]
ok i figured it out! it was cache path error. And some code error i fixed them

**Comment by BearDooks** [comment]
@ArtistSaihaan Thanks for the heads up. Was there anything in the plugin you needed to change?
