### ISSUE TITLE
[BUG] crash when not connected to internet

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#245]
**Describe the bug**
When your not connected to the internet, and you perform a task i.e. sending data to Firestore Database, the app crashes.

**To Reproduce**
Disable internet before submitting firebask task.
```
func upload_new_item(data : Dictionary):
	var firestore_collection : FirestoreCollection = Firebase.Firestore.collection(firestore_collection_id)
	var document_id = "document_id"
	var fields = data
	var add_task : FirestoreTask = firestore_collection.add(document_id, fields)
	var added_item : FirestoreDocument = yield(add_task, "task_finished")
	return added_item
```

**Expected behavior**
```
print(err code: Connection error   Error connecting to auth service)
return err
```
or something like that

**Screenshots**
![image](https://user-images.githubusercontent.com/37254287/136875049-5131880c-fb6d-4d3f-8c28-685bcf726421.png)

**Environment:**
 - Windows 10

**Additional context**

**Comment by BearDooks** [comment]
@shafnaz any update on this?

Thanks

Chuck

**Comment by shafnaz** [comment]
well I just log in like this:
![image](https://user-images.githubusercontent.com/37254287/139759166-c3da6f62-469e-41a6-be2a-9ee277e25a0b.png)
I disable my connection to wifi, and then run the project

**Comment by BearDooks** [comment]
OK. Can you break that code down for me since it does not look like the normal code we run.

I can only assume `userinfo` is another node somewhere?

Thanks

Chuck

**Comment by shafnaz** [comment]
Oh, right. Sorry about that.
![image](https://user-images.githubusercontent.com/37254287/139759539-25e62feb-6704-48bd-9bac-2eba90b99f7d.png)

pretty straight forward

**Comment by BearDooks** [comment]
What happens after that 4 second yield time. Can you share more of the code?

**Comment by shafnaz** [comment]
Well nothing relating to log in, I create a document after that. I just give it some space. The issue still happens even if I remove any code after that.

**Comment by shafnaz** [comment]
![image](https://user-images.githubusercontent.com/37254287/139768928-769e37e8-90f9-4cce-b09d-41f706785842.png)

**Comment by shafnaz** [comment]
hold on, I'm getting something else. I removed the login code, I still get the error, it's coming from something else

**Comment by shafnaz** [comment]
Alright let's close this issue, The error is coming from a scene. _process is running a code
