### ISSUE TITLE
[BUG] nextPageToken is returned as a String only. No key & string return.

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#258]
**Describe the bug**
`nextPageValue `only returns a string

**To Reproduce**
```
func query_collection_list():
	var add_task : FirestoreTask = Firebase.Firestore.list(firestore_collection_id, 3)
	var task_result = yield(add_task, "task_finished")
	print("result: ", task_result[task_result.size() - 1])
```
returns:

 AFTOeJwenuu5TLABMMWVpskruVa0RHYxt6D-WUKOhvsVD3-iXCduHUOoOAqooiM5wbpR-c3WLGp91JT3wRCb1OaGaZecfhTT9eI8YB-TcV--ypzM4UJDbZmG_0

This only returns a string

**Expected behavior**
returns:

next_page_token:  AFTOeJwenuu5TLABMMWVpskruVa0RHYxt6D-WUKOhvsVD3-iXCduHUOoOAqooiM5wbpR-c3WLGp91JT3wRCb1OaGaZecfhTT9eI8YB-TcV--ypzM4UJDbZmG_0

**Screenshots**
![image](https://user-images.githubusercontent.com/37254287/138591117-98c3acb7-5537-46a7-a4f0-4071e362251c.png)

**Environment:**
 -  Windows 10

**Comment by BearDooks** [comment]
@shafnaz Can you make a minimal project to demonstrate this, or share some more details. I have some time coming up where I might be able to look at it.

Thanks

Chuck

**Comment by WolfgangSenff** [comment]
Closing for now as we haven't heard back for about a year.
