### ISSUE TITLE
[FEATURE REQUEST] RemoteConfig implementation

### ISSUE THREAD

**Issue by WolfgangSenff** [GodotNuts/GodotFirebase#259]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to A/B test my games through Firebase and have them be tracked and what not, as well as updated and experimented on so I can come up with the best possible results.

**Describe the solution you'd like**
Simply put, I'd like RemoteConfig to be implemented so I can utilize it to implement the A/B testing. That will allow me to send updates to different users automatically and configure my game accordingly.

**Describe alternatives you've considered**
I've considered a few others, but it makes no real sense in a Firebase library. ;)

**Additional context**
Here's the discovery document for the REST API: https://firebaseremoteconfig.googleapis.com/$discovery/rest?version=v1

And here's a link to the definitions of everything in a cleaner format: https://firebase.google.com/docs/reference/remote-config/rest

**Comment by MeBadDev** [comment]
is RemoteConfig real time?

**Comment by WolfgangSenff** [comment]
Yes.

**Comment by WolfgangSenff** [comment]
This is now implemented, albeit not documented and very annoying to get to work. :)

**Comment by ZhangWei-bi** [comment]
@WolfgangSenff How do you make remote config work? I setup everything, then i call Firebase.RemoteConfigAPI.get_remote_config()

But I keep getting 
  [Firebase Error] >> { "content": "" }
[Firebase] >> Config request result: { "content": "" }
