### ISSUE TITLE
[BUG] Why is this error showing up: _resolve_hostname: getaddrinfo failed! Cannot resolve hostname.

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#260]
**Describe the bug**
I'm trying to make use of Storage, but keep getting the same error for all functions. I tried Put File, Put String, List All Objects. Everything else  is working, I can log in, send documents, get documents. My .env has all the values. I followed the wiki installation guide, all set up and working great. Now I'm trying out the Storage functions, it throws errors. I don't know if I'm missing something.

```
	var upload_task = Firebase.Storage.ref("listing_images/images (1).jpg").put_file("res://icons/images (1).jpg")
	yield(upload_task, "task_finished")
```
```
	var list_all_task = Firebase.Storage.ref("listing_images").list_all()
	yield(list_all_task, "task_finished")
	print(list_all_task.data)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/37254287/139360070-0d1b609d-6a0d-4abe-ad09-0efaba7df834.png)
![image](https://user-images.githubusercontent.com/37254287/139360242-8ef532da-fd37-4ef3-84ad-d76fab351b7d.png)

**Environment:**
 - OS:  Windows 10

**Comment by BearDooks** [comment]
@shafnaz 

I need to make sure that the plugin is using the right address for you when it is trying to upload. Can you please add the following line to `addons/godot-firebase/storage/storage.gd` by the following lines before the `_process_request(task)` on Line171

```
print("DEBUG DATA...")
print(task._url)
print("DEBUG DATA...")
```

This should print out the URL you are trying to connect to when uploading to storage. I would also suggest taking the `(1)` out of the name of the file. Normally I try to replace all spaces with either a `-` or an `_` since sometimes spaces can cause issues.

Thanks

Chuck

**Comment by shafnaz** [comment]
Alright, we're getting somewhere. Sorry, I have to remove part of the app name, those are only letters.

![image](https://user-images.githubusercontent.com/37254287/139543470-430d78c5-5faf-4418-952a-a2683cf16268.png)
![image](https://user-images.githubusercontent.com/37254287/139543482-166c3d63-70f5-4128-97c3-8eb6afbf0340.png)
![image](https://user-images.githubusercontent.com/37254287/139543524-17b1e301-272b-4119-929b-7f39bc3d80d9.png)

**Comment by shafnaz** [comment]
There is something strange with that print. what is the "o"

**Comment by BearDooks** [comment]
That is normal. I need to run some tests on my machine I thought it would print more, but maybe I need to add something else.

**Comment by BearDooks** [comment]
@shafnaz something weird is going on, you should see a `/v0/` at the start of your debug data
![image](https://user-images.githubusercontent.com/20961993/139593844-369da078-d604-43e6-9691-68a10dd33221.png)


Can you confirm these lines are the same in your storage.gd file

![image](https://user-images.githubusercontent.com/20961993/139593859-3854365c-0960-45b9-8bf8-616a00feea0d.png)

Thanks

Chuck

**Comment by shafnaz** [comment]
![image](https://user-images.githubusercontent.com/37254287/139752914-47598500-f839-4929-a0fe-921558b9dda9.png)

not the same

**Comment by shafnaz** [comment]
![image](https://user-images.githubusercontent.com/37254287/139753196-fde9676e-3664-4abc-a496-0965f0ff2514.png)

Also tried with that code, with no luck.
![image](https://user-images.githubusercontent.com/37254287/139753225-3c9d06db-a86d-44d9-b19f-a811208997a8.png)
![image](https://user-images.githubusercontent.com/37254287/139753268-312de19a-63f1-42b8-af5b-8cf134053049.png)

**Comment by BearDooks** [comment]
@shafnaz ok, this looks like an older version of the plugin. Can you please try this link to download a new copy.

https://github.com/GodotNuts/GodotFirebase/archive/refs/heads/main.zip

I would advise making a backup of the .env file, and then removing the entire addon folder. Then reinstall with this download. You can confirm it's the right version if your storage.gd has line 36 like mine.

Thanks

Chuck

**Comment by shafnaz** [comment]
You can check the latest release, that line is not updated
![image](https://user-images.githubusercontent.com/37254287/139753597-7575e426-a7a2-4d46-adde-8424f9d515fa.png)

**Comment by shafnaz** [comment]
ignore the above, i missed the url you sent

**Comment by shafnaz** [comment]
Works like a charm!

**Comment by BearDooks** [comment]
Awesome! Glad it worked!!
