### ISSUE TITLE
[BUG] Using integers as keys in Realtime Database causes crash after updating its values

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#266]
**Describe the bug**
Are we allowed to use integers as keys in Realtime Database?
After having connected to a reference path in Realtime Database, after I update values in the Realtime Database, I get an error in Godot. 

**To Reproduce**
1. In Godot, Connect to a Realtime Database path that contains integers as keys
![image](https://user-images.githubusercontent.com/37254287/142746472-c8f20028-6777-44f5-b5e7-501200430507.png)
2. Now update a value in one of those fields.
3. Godot will throw an error.

**Expected behavior**
No error.

**Screenshots**
This is the error I get when my data looks like this. See under "seats"
![image](https://user-images.githubusercontent.com/37254287/142746250-fb7725c1-6ce8-4bb3-aa4c-bc0a4f36aedb.png)
![image](https://user-images.githubusercontent.com/37254287/142746233-5435a7dc-fa71-4762-8eb9-769d326362a8.png)

When my data does not contain integers as keys, I get no error. See under "seats":
![image](https://user-images.githubusercontent.com/37254287/142746308-8894e284-a29d-423a-b0ed-9eb57c649e06.png)

**Environment:**
 - OS:  Windows 10

**Comment by BearDooks** [comment]
@shafnaz this might be Firebase doing this. I am not sure they store it as an integer, so it might be converted into a string. Can you try converting your side to a string before you use it? You would still be able to keep your numbers, but it would be a string instead of an integer

Thanks

Chuck

**Comment by shafnaz** [comment]
Sure.

**Comment by WolfgangSenff** [comment]
Even if that does work, I should note that you should not be using integers as your keys. There's a known issue with that in Firebase itself. When and where possible, you should be relying on Firebase's own key system by using "push" for lists - that's the whole point of the realtime database.
