### ISSUE TITLE
Firebase Hosting

### ISSUE THREAD

**Issue by gitumar** [GodotNuts/GodotFirebase#271]
Does GodotFirebase support firebase hosting? If not, how do we execute firebase hosting for Godot HTML deploy? Thanks

**Comment by WolfgangSenff** [comment]
It should! There isn't really anything to be done programmatically though. But I do know you can host a site and host a Godot game in it. You basically want to do it the same way you normally use hosting, I guess. @BearDooks has done this before - would you be able to write a quick summary of how to do it in the wiki, Chuck?

**Comment by BearDooks** [comment]
@gitumar , @WolfgangSenff is 100% correct. We did test this in the early days of working on this plugin. Let me find my notes from it and get something up in the wiki for you.

Chuck

**Comment by BearDooks** [comment]
@gitumar 

https://github.com/GodotNuts/GodotFirebase/wiki/FirebaseHosting

Please see this page. Its very easy to do this, which is why the wiki is pretty small for this section. Firebase will walk you through pretty much everything you need to do
