### ISSUE TITLE
[FEATURE REQUEST] Firebase Analytics

### ISSUE THREAD

**Issue by mars3142** [GodotNuts/GodotFirebase#274]
**Is your feature request related to a problem? Please describe.**
It would be great to use Firebase Analytics with your plugin.

**Describe the solution you'd like**
Because Firebase Analytics offers a web and c++ implementation, so there should be a REST api for it. There is also a Medium article about it: https://itnext.io/using-firebase-analytics-server-side-64ffacafa6c3

PS: Maybe you can find more within the official CPP SDK for Firebase -> https://github.com/firebase/firebase-cpp-sdk

**Comment by WolfgangSenff** [comment]
There is not - no REST API exists that is usable by the public. That said, we could attempt to make a similar call, but I'm reluctant to as the Firebase team has suggested it's capable of changing at any moment, and that the Measurement API does not fulfill the same requirements as Analytics. I'll leave this open for a bit as I review what that person did for the server side, but I'm hesitant to add anything that's not officially supported.
