### ISSUE TITLE
Is offline support for Cloud Firestore implemented?

### ISSUE THREAD

**Issue by kopkako** [GodotNuts/GodotFirebase#280]
Hi, just discovered this and really excited to try it out, looks great (and thanks for your work!)

Unfortunately, I require the Cloud Firestore offline functionality and read in the Wiki that
"Offline support - preliminary investigations have begun"

I then discovered issue #142 which was merged, so maybe this is already implemented and the Wiki is simply outdated?

**Comment by WolfgangSenff** [comment]
There are a few bugs with caching at the moment, but I haven't launched a full investigation into them yet. That said, the wiki is just out of date, yes. 😁 You should be able to at least try it and report back with bugs! I'm going to close this though, open a new bug if you find any please! I'll fix the wiki tomorrow, thanks for pointing it out.
