### ISSUE TITLE
[BUG] Issue with retrieving firestore data with same code on 2 machines

### ISSUE THREAD

**Issue by Kontrano** [GodotNuts/GodotFirebase#295]
**Describe the bug**
I have 2 PCs both running win11, Godot 3.4.3, same project. On one pc I can connect to Firestore and retrieve data just fine, on the other I cannot and get the Firebase Error "Unknown error when returning from task", 

 It seems to fail on the first get document that is on line 93/94 in App.gd, I have narrowed it down to getting a 404 response code from the _on_request_complete function in Firestore Task

I also have another project which has almost the same functionality with the same code that does work on both machines...?

I have included both project files in the download link here and messaged you the password for it on discord, My username is the same. For better reproducibility, I added the actual files I use hence the password-protected download.

Download:
https://send.tresorit.com/a#kmTN1WdmcyDEMENYF81KmQ 

**To Reproduce**
Run the code and press the login button with the already input credentials. 

**Expected behavior**
The relevant data should be retrieved from the document and after waiting about half a second you should see an image with some text next to it appear detailing an event with a time and location. see image:

![image](https://user-images.githubusercontent.com/80490564/172025673-4dbc73bc-7147-4b31-93e4-27725d27827b.png)

**Environment:**
Windows 11
Godot 3.4.3
Both PCs have a working internet connection but are at different physical locations and as such on different networks

If you need any additional information let me know

**Comment by BearDooks** [comment]
@Kontrano Did this ever solve itself? I had some weird issues with Firebase recently, and I swear Google is doing something on the backend.

Thanks

Chuck
