### ISSUE TITLE
send_password_reset_email -Signal [FEATURE REQUEST]

### ISSUE THREAD

**Issue by KpoJIuk06** [GodotNuts/GodotFirebase#303]
First I would like to thank you for the work you have done.
During the use of functions and signals, a password recovery signal was required.
To understand that if the letter is sent, issue a message about sending the letter, and if the wrong email is entered, then issue an error message.
Since the signals shown below, as well as in the documentation, none of them returned a response.

func _ready():
	Firebase.Auth.connect("login_succeeded", self, "_on_FirebaseAuth_login_succeeded")
	Firebase.Auth.connect("login_failed", self, "_on_FirebaseAuth_login_failed")	
	Firebase.Auth.connect("signup_succeeded", self, "_on_FirebaseAuth_signup_succeeded")
	pass 

func _on_FirebaseAuth_login_failed(error_code, message):
	print("error code: " + str(error_code))
	print("message: " + str(message))

func _on_FirebaseAuth_signup_succeeded(email):
	print("Sent a Reset password email!")
        Firebase.Auth.save_auth(email)

func _on_Reset_button_up():
	var email = $mail.text
	Firebase.Auth.send_password_reset_email(email)
	pass # Replace with function body.

**Comment by BearDooks** [comment]
@KpoJIuk06 Let me check with the team. I can't remember if this was going to be in an upcoming release. If not it looks like it should be not to bad to put in there.

Thanks

Chuck

**Comment by KpoJIuk06** [comment]
And also func _on_FirebaseAuth_request_completed(result_code, result_content):
print("result_request_code: " + str(result_code))
print("result_request_content: " + str(result_content))
Didnt get information if it wrong email. Only Login Failed call back

**Comment by KpoJIuk06** [comment]
Done . 
Thanks
func _on_FirebaseAuth_auth_request(result_code, result_content):
	print("result_auth_code: " + str(result_code)) 
	print("result_auth_content: " + str(result_content))
	if result_code != 1:
		$Notification.text = "Wrong email address"
	else:
		$Notification.text = "We just sent an email with a password reset link, please click the link to reset your password"

**Comment by BearDooks** [comment]
You shouldn't need to do some of that. The plugin has some builtin code to display errors in the console for things.

This is inside the `auth.gd` file

```
func _on_FirebaseAuth_request_completed(result : int, response_code : int, headers : PoolStringArray, body : PoolByteArray) -> void:
	print_debug(JSON.parse(body.get_string_from_utf8()).result)
	is_busy = false
	var res
	if response_code == 0:
		# Mocked error results to trigger the correct signal.
		# Can occur if there is no internet connection, or the service is down,
		# in which case there is no json_body (and thus parsing would fail).
		res = {"error": {
			"code": "Connection error",
			"message": "Error connecting to auth service"}}
	else:
		var bod = body.get_string_from_utf8()
		var json_result = JSON.parse(bod)
		if json_result.error != OK:
			Firebase._printerr("Error while parsing auth body json")
			emit_signal("auth_request", ERR_PARSE_ERROR, "Error while parsing auth body json")
			return
		res = json_result.result
```

you can probably parse out this message

**Comment by KpoJIuk06** [comment]
its enough for me with result code =)
