### ISSUE TITLE
[BUG] The wiki does not describe Cloud Functions correctly

### ISSUE THREAD

**Issue by jamespatrickleduc** [GodotNuts/GodotFirebase#304]
**Describe the bug**
The wiki describing Cloud Functions is incorrect.

**To Reproduce**
Go to the Cloud Functions page in the wiki: https://github.com/GodotNuts/GodotFirebase/wiki/Cloud-Functions

**Expected behavior**
The wiki should describe FirebaseFunctions and FunctionTasks, but instead the wrong classes are described.

**Comment by WolfgangSenff** [comment]
Oh for pity sake. Must have copy/pasted the page and forgot to update the values. I'll try to get these in this weekend while fixing a non-documentation bug.

**Comment by WolfgangSenff** [comment]
I have updated the page, feel free to check it out now. I haven't tested it because I'm not in a position to, but it's pretty straight-forward; feel free to let us know with a new issue if you run into anything unexpected or borked.

**Comment by fenix-hub** [comment]
Hi, I've added an example in the wiki page
https://github.com/GodotNuts/GodotFirebase/wiki/Cloud-Functions
