### ISSUE TITLE
[BUG] Firebase Function with GET method doesn't pass parameters (with possible solution)

### ISSUE THREAD

**Issue by adavidm** [GodotNuts/GodotFirebase#306]
**Describe the bug**
I was having trouble using Firebase Functions, where the parameters are not being passed to Firebase. I think I have identified the cause.

**To Reproduce**
- Call a Firebase Function using the GET method with parameters. 
- The parameters will not be included in the request

**Expected behavior**
A clear and concise description of what you expected to happen, for example:

parameters should be passed through to Firebase

*** possible solution ***

Looking at functions.gd, it appears that the _url parameter is being passed to function_task too early:

```
    var url : String = _base_url + ("/" if not _base_url.ends_with("/") else "") + function
    function_task._url = url

    if not params.empty():
        url += "?"
        for key in params.keys():
            url += key + "=" + params[key] + "&"
```

I've tried moving the assignment after the loop and it seems to work for me now

**Comment by fenix-hub** [comment]
Yes indeed, your solution was the intended one.
Mind creating a pull request, if you feel like contributing?

**Comment by adavidm** [comment]
sure, I've never done that before so hopefully not too difficult. Will give it a go now.

**Comment by adavidm** [comment]
That's done:

https://github.com/GodotNuts/GodotFirebase/pull/307
