### ISSUE TITLE
[FEATURE REQUEST] - Remove Firestore caching by default

### ISSUE THREAD

**Issue by WolfgangSenff** [GodotNuts/GodotFirebase#314]
**Is your feature request related to a problem? Please describe.**
Firestore caching has caused us a ton of problems, from occasionally sending people into offline mode when they shouldn't be, to just causing weird errors. We'd like to get rid of it.

**Describe the solution you'd like**
It should be easy enough to remove, or at the least just turn off by setting the flag for it to false by default instead of true.

**Describe alternatives you've considered**
Users could do this manually, but if it's so buggy, they should not have to.

**Additional context**

**Comment by Kontrano** [comment]
I Agree with this. I also had multiple issues with it and forgot that it existed and was on by default at first which caused me about a week of headaches trying to troubleshoot.

**Comment by hjiul** [comment]
I think i also run into cache trouble but im not sure.

50-70% of the time i run my request to get a document it consider i'm offline and try to go to the cache.
The auth works very well and my internet connection is fine.

The request works sometimes so its weird.
Not sure what to do but I can see that the addon considerim offline (maybe i can extend the delay to wait for a server answer or something like that ? )

**Comment by WolfgangSenff** [comment]
> I think i also run into cache trouble but im not sure.
> 
> 50-70% of the time i run my request to get a document it consider i'm offline and try to go to the cache. The auth works very well and my internet connection is fine.
> 
> The request works sometimes so its weird. Not sure what to do but I can see that the addon considerim offline (maybe i can extend the delay to wait for a server answer or something like that ? )

This is exactly the issue you're running into. Go into your .env file and delete the path to the cache (leave the key but remove the value), then go find the cache itself from what you deleted and delete what's there. That will probably fix this for you.
