### ISSUE TITLE
[BUG] get_google_auth_manual() not functioning as inteded

### ISSUE THREAD

**Issue by Blockyheadman** [GodotNuts/GodotFirebase#318]
**Describe the bug**
It takes me to an error page when it opens the URL

**To Reproduce**
1. use get_google_auth_manual()
2. see error page

**Expected behavior**
Allows for the user to click on their google account and get an authorization code.

"firestore_collection.add("DOCUMENT_ID", {'name': 'Document Name', 'active': 'true'}) should add a document to my Firestore Collection"

**Screenshots**

**Environment:**
 - OS: Windows 10
 - Browser Edge

**Additional context**

**Comment by WolfgangSenff** [comment]
Manual auth has been deprecated recently by Google for being insecure. We'll be updating the plugin to remove the possiblity of even trying to use it.

**Comment by WolfgangSenff** [comment]
Will update here when we've done that.

**Comment by WolfgangSenff** [comment]
Going to go ahead and close this, as it's already handled by the following:

https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management#login-with-oauth-automatic

And if needed you can go through the extra OAuth steps found here:
https://github.com/GodotNuts/GodotFirebase/wiki/Installation-and-Activation#additional-oauth-configuration
