### ISSUE TITLE
[BUG] Wiki page is outdated

### ISSUE THREAD

**Issue by MeBadDev** [GodotNuts/GodotFirebase#321]
in the 'auth' section, i copied code `Firebase.Auth.signup_with_email(email,password)` but find its not working, after some searching i think its renamed to `signup_with_email_and_password`. it should be update or something

**Comment by MeBadDev** [comment]
[(here is the link)](https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management#signup-with-email)

**Comment by fenix-hub** [comment]
Thanks, wiki updated :)
