### ISSUE TITLE
Duplicate entry on Firestore wiki

### ISSUE THREAD

**Issue by domiva** [GodotNuts/GodotFirebase#342]
I noticed that in the wiki for the Firestore functionality there is a duplicate entry under the [get a document](https://github.com/GodotNuts/GodotFirebase/wiki/Firestore#get-a-document) section. Step 2 exists twice as far as I can tell, with duplicates for some of the code.

**Comment by BearDooks** [comment]
@domiva you are 100% correct. I will work with the team to get this fixed

**Comment by BearDooks** [comment]
This should be fixed now
