### ISSUE TITLE
[BUG] Outdated example in docs

### ISSUE THREAD

**Issue by phil-hudson** [GodotNuts/GodotFirebase#345]
**Describe the bug**
Authentication and user management docs are outdated:

```
func _on_FirebaseAuth_login_succeeded(auth):
	var user = await Firebase.Auth.get_user_data()
	print(user)
	
```

this should instead set a connection in ready and print this in the signal

On this page toward the bottom:

https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management#get-user-data

**Comment by WolfgangSenff** [comment]
No - what's there is completely valid. By calling await, it will wait for get_user_data() to return and hand the user back to you, or it should. If that doesn't work, then that's a different bug, so closing this.

**Comment by phil-hudson** [comment]
Take a look at:

_on_FirebaseAuth_request_completed
https://github.com/GodotNuts/GodotFirebase/blob/a0c55125c3643c53c7888ded7103352f36e23318/addons/godot-firebase/auth/auth.gd#L418

you can see it only emits the signal with the data, the function itself returns void.

I just tested implementing the example, and found it didn't work - using the signal method does work.

**Comment by WolfgangSenff** [comment]
I have updated the documentation accordingly. Good find!
