### ISSUE TITLE
[BUG] FirestoreQuery.select with array as parameter results in 400.

### ISSUE THREAD

**Issue by tzrot-jed** [GodotNuts/GodotFirebase#349]
**Describe the bug**
Passing an array to FirestoreQuery.select doesn't format the query request to Firestore properly and results in a 400

**To Reproduce**
Assuming a Firestore collection _stage_ with fields _name_ and _rating_:
Running:
```
var query: FirestoreQuery = FirestoreQuery.new().select(["name", "rating"]).from("stage", false)
var task: FirestoreTask = Firebase.Firestore.query(query)
var result: Array = yield(task, "result_query")
```

Results in a 400 response by Firestore

**Expected behavior**
 ```
var query: FirestoreQuery = FirestoreQuery.new().select(["name", "rating"]).from("stage", false)
var task: FirestoreTask = Firebase.Firestore.query(query)
var result: Array = yield(task, "result_query")
```
 should request Firestore with  ` {fields:[{fieldPath:name}, {fieldPath:rating}]}` instead of  `{fields:[name, rating]}`

**Screenshots**
Not applicable

**Environment:**
 - OS: Windows 11
 - Godot 3.5.2

**Additional context**
I will be submitting a PR with a fix

**Comment by WolfgangSenff** [comment]
That is super weird. I will have to look into this closer. Very interesting. Thanks for submitting it! Will probably merge it soon, just haven't had time lately to validate it or anything.
