### ISSUE TITLE
I did not find the .env essential for the plugin

### ISSUE THREAD

**Issue by NonoIceOff** [GodotNuts/GodotFirebase#351]
Hello, I followed carefully in the wiki, the installation steps for the Plugin on Godot 4.0.3, but while launching the application to test I had this error in the debugger "[Firebase Error] >> Unable to read .env file at path 'res://addons/godot-firebase/.env'"

Tried to git clone the project seeing that there was an .env, there isn't
I took the plugin for Godot 4.0.x

![image](https://github.com/GodotNuts/GodotFirebase/assets/54319211/be66f62a-71a1-4ebd-b11e-23d624148062)

**Comment by WolfgangSenff** [comment]
You have to create that file yourself - it is not included because it contains credentials that you do *not* want to store in GitHub. It often caused issues for people accidentally including them, so we decided to simply remove it.
