### ISSUE TITLE
[FEATURE REQUEST] Add an example for order_by_fields to the docs

### ISSUE THREAD

**Issue by bsarsgard** [GodotNuts/GodotFirebase#354]
**Is your feature request related to a problem? Please describe.**
The order_by_fields method is a bit confusing; an example would be helpful.

**Describe the solution you'd like**
Please see this PR for a suggested example to add:
https://github.com/bsarsgard/GodotFirebaseWiki/pull/1/files

**Describe alternatives you've considered**
Any other example you think would be better!

**Additional context**
I think that covers it

**Comment by BearDooks** [comment]
@bsarsgard Thanks, and you are right. I have added your code into the wiki!
