### ISSUE TITLE
Server timestamp

### ISSUE THREAD

**Issue by thisisjamaldin** [GodotNuts/GodotFirebase#355]
**Is your feature request related to a problem? Please describe.**
One of the big issues in creating a game is avoiding time hacking, so I would like to set Real Server Time in firestore

**Describe the solution you'd like**
In android I could create a model with @Timestamp annotation and leave it null 

**Describe alternatives you've considered**
I can use free api (can't rely on) to get current time

**Additional context**
I use Godot 3.5.2 gdscript, can you please implement that to this version.

**Comment by WolfgangSenff** [comment]
I'll implement it to both. :) It will take me a bit though, as I'm very busy!

**Comment by JekSun97** [comment]
I'm also waiting for 3.5.2+ :)

**Comment by WolfgangSenff** [comment]
This is implemented in 4.x. I actually have realized it wouldn't be wildly different in 3.x, so I'll be able to backport it to that. @thisisjamaldin and @JekSun97 - do you both still need it?

**Comment by thisisjamaldin** [comment]
I might need it later, I'm on other project. After testing 3 and 4 on android, 3 had more fps and graphics was better so I used v.3

**Comment by WolfgangSenff** [comment]
Got it! Well, I'll try to backport it when I can.

**Comment by WolfgangSenff** [comment]
I'm going to close this for now. I will attempt to implement it for 3.x when I can though, see if it makes sense to just backport what I have directly and update the signal usage, but it's hard to say.
