### ISSUE TITLE
[BUG] Cannot store integers as keys for dictionary, only Strings.

### ISSUE THREAD

**Issue by shafnaz** [GodotNuts/GodotFirebase#357]
**Describe the bug**
I would like to store my enumerator types as keys in the dictionary and do an add_document. 
![image](https://github.com/GodotNuts/GodotFirebase/assets/37254287/816a0f87-76e0-4e87-9148-74c28b716d9e)
![image](https://github.com/GodotNuts/GodotFirebase/assets/37254287/10fbb511-a86d-4e29-a801-07592ab2dd12)

**Comment by WolfgangSenff** [comment]
I will likely fix this today. I'm not sure if it'll work within Firebase itself, but good find!

**Comment by shafnaz** [comment]
Thank you

**Comment by shafnaz** [comment]
Pretty busy, any progress so far?

**Comment by WolfgangSenff** [comment]
I have not had a chance to yet, sorry! Life's taken over for a bit.

**Comment by WolfgangSenff** [comment]
Believe it or not, I have a potential fix for this ready - just working on part of my big refactor for Firestore and figured out how I wanted to do it. I know it's quite a while later, so sorry about that! But this will be merged soon, and when I do, I'll close this and mention the PR in which it's fixed.

**Comment by WolfgangSenff** [comment]
This has been resolved with my most recent massive refactoring of Firestore. See https://github.com/GodotNuts/GodotFirebase/wiki/Upgrade-Guide-to-4.x-version-2 for more.
