### ISSUE TITLE
Firebase Realtime Database DataSnapshot

### ISSUE THREAD

**Issue by mcoswel** [GodotNuts/GodotFirebase#365]
Apologize for my English, I would like a feature where you could get DataSnapshot of Realtime database. Thank you

**Comment by WolfgangSenff** [comment]
That already exists - it's not the exact same as the main libraries, but you can get the snapshot from the database reference by using the new_data_update signal.

**Comment by mcoswel** [comment]
> That already exists - it's not the exact same as the main libraries, but you can get the snapshot from the database reference by using the new_data_update signal.

Nope. DataSnapshot is like one time requesting and you get the whole data. new_data_update is emitted for every key. For example:
-Parent
  - child1
      - data
  - child2
      - data
new_data_update will emit 2 times when you get_database_reference of "Parent"

**Comment by mcoswel** [comment]
> It's the same as just getting it the first time at the highest level you're trying to get. That said, we have a bug currently with it where it'll just keep going, and I know some people have asked for similar where you can just get it once. I'll see about implementing it at some point.

Thank you very much Sir. Would like to see it implemented. Or maybe create a signal which will be emitted when the new_data_update finish it's job.

**Comment by WolfgangSenff** [comment]
That's good conceptually, but the way it's implemented, it's never finished. :P I will still try to come up with something smart. This one is going to take a while though! Going to require quite a lot of work and document reading. But it's good to bring up! So thank you for posting.
