### ISSUE TITLE
[FEATURE REQUEST] If I don't do Firebase authentication, can't I request Functions?

### ISSUE THREAD

**Issue by greatsk55** [GodotNuts/GodotFirebase#369]
**Is your feature request related to a problem? Please describe.**

I'm trying to do firebase Auth using Cloud Functions.

If you send the email and password to functions, functions will process the membership and save the relevant data in the Firrestore

Sending an auth request causes a Firebase authentication error.
"[Firebase] >> Unauthenticated request issued..."

**Describe the solution you'd like**

I think we need to approach functions without auth, but if that's not the case

It seems that the pirestore needs a function to wait for data to change.

**Comment by WolfgangSenff** [comment]
Yeah, we want to work on removing forced authentication throughout the entire library. It's somewhat difficult, simply because it's so huge.

**Comment by WolfgangSenff** [comment]
So to answer the question, right now, no, you cannot. :/ Sorry. You can do anonymous auth if you need to. I will hopefully be able to get to removing forced authentication sometime in the next few months, but we'll see.
