### ISSUE TITLE
[BUG] Godot won't include .env file while exporting the project

### ISSUE THREAD

**Issue by zimlewis** [GodotNuts/GodotFirebase#370]
**Describe the bug**
Godot isn't able to include .env file while exporting anymore

**To Reproduce**
I just casually export my godot project with firebase addons and when I tried to use my authentication it returned a 403 error: the request is missing a valid api key

**Expected behavior**
The authentication works well in my the editor

**Screenshots**
![image](https://github.com/GodotNuts/GodotFirebase/assets/136766037/b6b5325c-705b-4080-986b-c4cffc8d179b)
![image](https://github.com/GodotNuts/GodotFirebase/assets/136766037/be35b1c0-3a0d-415e-929e-ed26c01d2ff1)

**Environment:**
 - OS: Ubuntu 22.04.3 LTS

**Comment by fenix-hub** [comment]
Make sure to follow our [wiki](https://github.com/GodotNuts/GodotFirebase/wiki/Installation-and-Activation#exporting-important) when exporting your projects with Firebase.
The *.env file should be manually added in the list of exported resources.

**Comment by WolfgangSenff** [comment]
> Make sure to follow our [wiki](https://github.com/GodotNuts/GodotFirebase/wiki/Installation-and-Activation#exporting-important) when exporting your projects with Firebase. The *.env file should be manually added in the list of exported resources.

Apparently that doesn't work - the rules of Godot are such that it won't include anything that starts with just a period. I'm not sure if the * makes a difference - it's possible, but I got the impression it didn't.

**Comment by 2d-Peasant** [comment]
> > Make sure to follow our [wiki](https://github.com/GodotNuts/GodotFirebase/wiki/Installation-and-Activation#exporting-important) when exporting your projects with Firebase. The *.env file should be manually added in the list of exported resources.
> 
> Apparently that doesn't work - the rules of Godot are such that it won't include anything that starts with just a period. I'm not sure if the * makes a difference - it's possible, but I got the impression it didn't.

I tested it in my project, with both "*" and without it. For android export (godot3.5) it works only if "*" included. I didn't test it in other exports.

Btw it's irrelevant to this topic, nevertheless i would like to ask when the "once" feature would be added to v3.5 as well :P thanks!

**Comment by 2d-Peasant** [comment]
> That is already added, though not to 3.5 yet, has to wait until this weekend.

Thanks for the update!

**Comment by WolfgangSenff** [comment]
@zimlewis - can you test this using *.env as the export value? If that works, then I can close this and just update the wiki.

**Comment by 2d-Peasant** [comment]
I guess he is away, tho i tried it on windows 10 OS and it worked there as well, just so as a note.

Anyway, have u got time for a possible 3.5 update?

**Comment by WolfgangSenff** [comment]
At the moment, no - work is tight right now. It's not a difficult change though, if you want to just look at what I did and do it locally for yourself in 3.5, or if you want to open a PR for it - would be much appreciated!
