### ISSUE TITLE
The plugin dosn't want to work in Godot v4.2.1 ??

### ISSUE THREAD

**Issue by CodeCrusherMedo** [GodotNuts/GodotFirebase#374]
**Describe the bug**
i have godot engine v4.2.1 and i follow every thing in the starting guide but when i try to run a basic script, it doesn't want to work.
it gives me an error in the editor

**To Reproduce**
i just make a simple UI scene with a button and attach a scipt to it so when i press the button it get data from firebase database

`var firebaseob = Firebase.Firestore.collection("/Novels Info")`

**Screenshots**
i got this error when i try to get the script to work :

![image](https://github.com/GodotNuts/GodotFirebase/assets/154018087/aad04340-cb4d-4644-9fce-a64a96f696ca)

**Environment:**
 - OS: windows 10
 - Godot : v4.2.1
 - Godot firebase v5.2

I am not sure what is happening

**Comment by CodeCrusherMedo** [comment]
i also notice something else in a lot of the add-on scripts, it give me some sort of error "couldn't find type something": 

![image](https://github.com/GodotNuts/GodotFirebase/assets/154018087/bdd78516-ea58-4c5a-b214-e4d32b843af6)

![image](https://github.com/GodotNuts/GodotFirebase/assets/154018087/132197e1-7817-4598-b7b6-e15f088ac545)

![image](https://github.com/GodotNuts/GodotFirebase/assets/154018087/392bf9a0-c82f-4cf4-b0a2-6f8a9af94c04)

![image](https://github.com/GodotNuts/GodotFirebase/assets/154018087/cc775d90-853d-4ac5-bab6-6657319f9b06)

**Comment by CodeCrusherMedo** [comment]
just now I try to use Godot v4.1.1 and no errors. so i thing the plugin isnot comapatable with 4.2.1 yet ??

**Comment by WolfgangSenff** [comment]
It works fine in 4.2.1 (I just ran it in my test harness - you can find the test harness in our repo, including one with 4.x support on a different branch). I think probably you either downloaded the 3.x version by mistake, or it has cached your build. If you try closing Godot, then going into your project's folder and deleting your .godot folder, then re-opening your project in 4.2.1 or whatever version, it should work I think.

**Comment by WolfgangSenff** [comment]
Looks like you didn't do 3.x, so try the .godot folder delete thing. This is a common issue with Godot when upgrading projects or things like that. When and where did you download the plugin? Like I said, I have it working just fine, no changes needed, in several projects, would be weird if it only didn't work for you because the plugin is wrong.

**Comment by CodeCrusherMedo** [comment]
thanks alot it work just fine after i delete the .godot folder thing thanks alot 😊
