### ISSUE TITLE
[BUG] It wont work on Godot 4.2 Stable

### ISSUE THREAD

**Issue by ALI3D69** [GodotNuts/GodotFirebase#375]
**Describe the bug**
When I add addon folder in the godot, I get many error that says:
Failed to load script "..." with error parse error.

**To Reproduce**
I just add this 3 folder in the addons folder.

**Expected behavior**
not having error!

**Screenshots**
![image](https://github.com/GodotNuts/GodotFirebase/assets/5319306/f39b7dcd-9f3c-4f53-a1e4-c59621f1ea2f)

**Environment:**
 - OS: [Windows 10]
 - Godot 4.2 Stable

**Additional context**
all the errors:
  res://addons/godot-firebase/auth/providers/facebook.gd:2 - Parse Error: Could not find base class "AuthProvider".
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/providers/facebook.gd" with error "Parse error". (User)
  res://addons/godot-firebase/auth/providers/github.gd:2 - Parse Error: Could not find base class "AuthProvider".
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/providers/github.gd" with error "Parse error". (User)
  res://addons/godot-firebase/auth/providers/google.gd:2 - Parse Error: Could not find base class "AuthProvider".
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/providers/google.gd" with error "Parse error". (User)
  res://addons/godot-firebase/auth/providers/twitter.gd:2 - Parse Error: Could not find base class "AuthProvider".
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/providers/twitter.gd" with error "Parse error". (User)
  res://addons/godot-firebase/auth/auth.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/auth.gd" with error "Parse error". (User)
  res://addons/godot-firebase/auth/auth_provider.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/auth_provider.gd" with error "Parse error". (User)
  res://addons/godot-firebase/auth/user_data.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/auth/user_data.gd" with error "Parse error". (User)
  res://addons/godot-firebase/database/database.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/database/database.gd" with error "Parse error". (User)
  res://addons/godot-firebase/database/database_store.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/database/database_store.gd" with error "Parse error". (User)
  res://addons/godot-firebase/database/reference.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/database/reference.gd" with error "Parse error". (User)
  res://addons/godot-firebase/database/resource.gd:4 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/database/resource.gd" with error "Parse error". (User)
  res://addons/godot-firebase/dynamiclinks/dynamiclinks.gd:6 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/dynamiclinks/dynamiclinks.gd" with error "Parse error". (User)
  res://addons/godot-firebase/firebase/firebase.gd:11 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/firebase/firebase.gd" with error "Parse error". (User)
  res://addons/godot-firebase/firestore/firestore.gd:15 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/firestore/firestore.gd" with error "Parse error". (User)
  res://addons/godot-firebase/firestore/firestore_collection.gd:6 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/firestore/firestore_collection.gd" with error "Parse error". (User)
  res://addons/godot-firebase/firestore/firestore_document.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/firestore/firestore_document.gd" with error "Parse error". (User)
  res://addons/godot-firebase/firestore/firestore_query.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/firestore/firestore_query.gd" with error "Parse error". (User)
  res://addons/godot-firebase/firestore/firestore_task.gd:20 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/firestore/firestore_task.gd" with error "Parse error". (User)
  res://addons/godot-firebase/functions/functions.gd:7 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/functions/functions.gd" with error "Parse error". (User)
  res://addons/godot-firebase/functions/function_task.gd:12 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/functions/function_task.gd" with error "Parse error". (User)
  res://addons/godot-firebase/storage/storage.gd:7 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/storage/storage.gd" with error "Parse error". (User)
  res://addons/godot-firebase/storage/storage_reference.gd:5 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/storage/storage_reference.gd" with error "Parse error". (User)
  res://addons/godot-firebase/storage/storage_task.gd:4 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/storage/storage_task.gd" with error "Parse error". (User)
  res://addons/godot-firebase/plugin.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/godot-firebase/plugin.gd" with error "Parse error". (User)
  res://addons/http-sse-client/HTTPSSEClient.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/http-sse-client/HTTPSSEClient.gd" with error "Parse error". (User)
  res://addons/http-sse-client/httpsseclient_plugin.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/http-sse-client/httpsseclient_plugin.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_exporter/doc_exporter.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_exporter/doc_exporter.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_exporter/editor_help_doc_exporter.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_exporter/editor_help_doc_exporter.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/argument_doc_item.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/argument_doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/class_doc_item.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/class_doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/constant_doc_item.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/constant_doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/doc_item.gd:2 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/method_doc_item.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/method_doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/property_doc_item.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/property_doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/doc_item/signal_doc_item.gd:3 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/doc_item/signal_doc_item.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/class_doc_generator.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/class_doc_generator.gd" with error "Parse error". (User)
  res://addons/silicon.util.custom_docs/plugin.gd:1 - Parse Error: Unexpected "Identifier" in class body.
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://addons/silicon.util.custom_docs/plugin.gd" with error "Parse error". (User)

**Comment by WolfgangSenff** [comment]
There are two possible problems with your setup. Either you have the wrong version and got the 3.x version by accident, or need to reimport. To reimport, close Godot, go into your project's folder, delete the .godot folder, then reopen the project. It'll reimport everything and you should be fine.

**Comment by ALI3D69** [comment]
I create a new project with 4.2 stable and I still have the same problem!
![image](https://github.com/GodotNuts/GodotFirebase/assets/5319306/9d045b7d-a9da-46d7-ac50-02e94fe5e54a)

for example you didnt put the @ character in this script!
![image](https://github.com/GodotNuts/GodotFirebase/assets/5319306/4acd0523-e7dc-4137-8c08-2be190dbea6a)
Am I downloading the wrong SDK?

**Comment by WolfgangSenff** [comment]
You must have the wrong version then! Make sure to get the 4.x version if you're downloading it directly! If you pick the main branch, that's for 3.x.

**Comment by ALI3D69** [comment]
Thanks. I was in main branch.
but I still have some problems with 4.x branch.
It says:
res://addons/godot-firebase/auth/auth.gd:175 - Parse Error: Identifier "Firebase" not declared in the current scope.

![image](https://github.com/GodotNuts/GodotFirebase/assets/5319306/e9841050-60b4-4e44-bd7a-a70c445264f9)

**Comment by WolfgangSenff** [comment]
Like I said: close your project, delete your .godot folder from the project's folder, then re-open the project now that you have the right version.

**Comment by ALI3D69** [comment]
I delete the .godot folder. I even create a new project. It says Firebase not declared in the current scope!
shouldnt be a "class_name Firebase" in the firebase.gd? or anywhere else?

**Comment by WolfgangSenff** [comment]
It should be a singleton. Did you enable the plugin?

**Comment by ALI3D69** [comment]
Thank you. I fix it with enabling plugin!

**Comment by ALI3D69** [comment]
thanks to you my problem is fixed only to realize that there is no analytics! I have one more question.
Is it hard to implement analytics? Why it is not already implemented in the SDK?

**Comment by WolfgangSenff** [comment]
The REST API does not support analytics. To use it, you have to use one of the mobile-specific platforms, unfortunately, which our library does not include.
