### ISSUE TITLE
[BUG] Godot 4 doesn't have "JavaScript" feature tag anymore.

### ISSUE THREAD

**Issue by kyboon** [GodotNuts/GodotFirebase#379]
**Describe the bug**
I was trying to get the Firebase OAuth working on Godot 4, the desktop build worked fine but the web build failed. Upon inspection I found out that in `auth.gd`, `get_token_from_url()` function, the line `OS.has_feature('JavaScript')` always return false.

**To Reproduce**
Any implementation of OAuth on web build should fail.

**Expected behavior**
`get_token_from_url()` should return the token.

**Environment:**
Godot 4.2.stable.official
Browser: Chrome, Edge

**Additional context**
According to the Godot documentation [](https://docs.godotengine.org/en/stable/tutorials/export/feature_tags.html), the tag "JavaScript" has been removed.
I've tried to replace the faulty line with `OS.has_feature('web')` and it worked, `get_token_from_url()` is now returning the expected result, and the "Sign in with Google" worked perfectly for my web build. I'm current using this as a workaround.

**Comment by WolfgangSenff** [comment]
Well that's a good find! Do you want to open a PR with the fix, or no?

**Comment by kyboon** [comment]
I'm not sure which branch is for godot 3 and which is for godot 4, which is
why I didn't create a PR instead.

**Comment by WolfgangSenff** [comment]
Main is 3.x, and the branch labeled 4.x is for 4.

**Comment by kyboon** [comment]
PR created. #380

**Comment by WolfgangSenff** [comment]
Fixed by #380 .
