### ISSUE TITLE
[FEATURE REQUEST] Firebase Auth - Convert an anonymous account to a permanent account

### ISSUE THREAD

**Issue by carmex** [GodotNuts/GodotFirebase#382]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to convert an anonymous Firebase account to a permanent account as described here: https://firebase.google.com/docs/auth/web/anonymous-auth#convert-an-anonymous-account-to-a-permanent-account

**Describe the solution you'd like**
Would like method(s) added to auth.gd to support this workflow.

**Describe alternatives you've considered**
I have considered some cloud functions that would migrate user data from the original anonymous account into the newly created account but this seems sub-optimal when a more general solution is possible.

**Comment by WolfgangSenff** [comment]
Closed by #391.
