### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by isthargames** [GodotNuts/GodotFirebase#386]
**Login window error**
After configuring the entire plugin for correct operation, when testing it on PC it works very well and the message appears after a correct login, that is, "🔥 You can close this window now. 🔥".

But trying on android doesn't work, sometimes it logs in, sometimes it doesn't but an error window always appears.

**I have a test button set up like this:**
![3](https://github.com/GodotNuts/GodotFirebase/assets/149918776/9337fb5a-e984-4007-9167-96cc41943047)

_I tried this configuration so that the error window would stop appearing after successful login on Android._

![image](https://github.com/GodotNuts/GodotFirebase/assets/149918776/b35e172e-e173-42a0-9bff-3f378f19fc23)

**But I still get this error in the browser:**

![image](https://github.com/GodotNuts/GodotFirebase/assets/149918776/18c08376-2262-4c68-89aa-059b67ec74da)

I would be very grateful if you could give me a solution, thanks for reading.

**Comment by WolfgangSenff** [comment]
Unfortunately, as you can see here, https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management#list-of-providers, Android is not supported for this type of login. I'm going to go ahead and close this, as there's nothing we can do about it - the Android OS itself prevents us from implementing a solution.

**Comment by charleslemaux** [comment]
Hi, I also misread the documentation and ran into the same issue, what solution did you end up using ?
