### ISSUE TITLE
[BUG] Invalid get index 'fields' (on base: 'Dictionary').

### ISSUE THREAD

**Issue by lukethomas1** [GodotNuts/GodotFirebase#401]
(Godot 4)
When running a simple `var document = FirestoreDocument.new()`, I get the above error `Invalid get index 'fields' (on base: 'Dictionary').`. I've traced the error to this [line of code](https://github.com/GodotNuts/GodotFirebase/blame/eb1f83fe1a803e69b6e8f67d968d76d66c66e066/addons/godot-firebase/firestore/firestore_document.gd#L24) which was updated 3 days ago. The Godot [Dictionary docs](https://docs.godotengine.org/en/stable/classes/class_dictionary.html) don't have any mention of a 'fields' variable, so it seems like this is a bug in the plugin rather than on my end, however I'd be happy to supply information or code snippets if necessary for debugging.

EDIT: I realized the Dictionary.fields syntax will get the 'fields' key out of the dictionary. However, despite that, using FirestoreDocument.new() will still fail because the default arg is an empty Dictionary. Is there an example of the proper usage for adding/updating a document using the FirestoreCollection object?

**Comment by WolfgangSenff** [comment]
You should not be using new on it. You have to get the document from Firestore the first time, or add it through a collection the first time. That will initialize it for you. Unfortunately, with the way Godot is setup, there's no way for me to restrict that. So check out the wiki and the upgrade guide and there's examples in it.
