### ISSUE TITLE
[BUG] Firebase Storage Invalid Index

### ISSUE THREAD

**Issue by HuskyDreaming** [GodotNuts/GodotFirebase#402]
Firebase Storage has problems with indexing.

**To Reproduce**
Create any reference to path in the bucket.

**Expected behavior**
When the correct rules have been setup for firebase:
Firebase.Storage.ref().get_data should return required data

**Screenshots**
![image](https://github.com/GodotNuts/GodotFirebase/assets/86812277/8965bf6d-20fe-40d5-9367-4641b42ce3c0)
![image](https://github.com/GodotNuts/GodotFirebase/assets/86812277/b3c3286a-778c-4dcd-847a-9af6f577c511)

**Environment:**
 - OS: Android, Windows 10

**Additional context**
This topic has already been discussed in discord:
https://discord.com/channels/794559524903714886/888779604007993354/1248785442237583410

**Comment by WolfgangSenff** [comment]
Aside from having discussed this already with you, it's an easy fix - you can just remove the -1 index and replace it with `back()` I believe it is. That said, I'll fix it in the plugin, just letting you know what the fix is probably going to be! :P And that I've seen this and haven't forgotten it.

**Comment by WolfgangSenff** [comment]
Oh! I lied. I already fixed it, so I'm closing this. :)
