### ISSUE TITLE
[FEATURE REQUEST] How to push notification by FCM

### ISSUE THREAD

**Issue by duongxinh2003** [GodotNuts/GodotFirebase#405]
**Is your feature request related to a problem? Please describe.**
I want to push notifications through Firebase FCM token, but I cannot find the document about how to do it

**Additional context**
- Godot version 4.x

**Comment by WolfgangSenff** [comment]
Unfortunately, we cannot support FCM as it requires a custom export template - otherwise, we cannot ever receive those push tokens effectively. You can replace this functionality with the Realtime Database however.
