### ISSUE TITLE
[BUG] update function is not working in 4.2.2 

### ISSUE THREAD

**Issue by CraigMLdsouza** [GodotNuts/GodotFirebase#410]
**Describe the bug**
I'm trying to call the update function on a collection using collection.update(document) where document is of type: FirestoreDocument. tried adding the name and field in dictionary format but it still doesnt work. I'm a little confused regarding the how the update function is to be used in the documentation as well.

**To Reproduce**
func save_data():
	var auth = Firebase.Auth.auth
	if auth.localid:
		var collection: FirestoreCollection = Firebase.Firestore.collection(COLLECTION_ID)
		var document = FirestoreDocument.new({"name": auth.localid, "fields": {'oranges': oranges}})
		var task = await collection.update(document)
		
**Environment:**
 - OS: [ Windows 10]
 - Browser [edge]

**Comment by WolfgangSenff** [comment]
That is not how you create a document at the moment. If you want to _add_ a document to Firestore, then the above is how you do it. It is required at the moment that, if you have a document in Firestore for it already, you have to get it first and _then_ update it by updating the document. This is all documented in the wiki.

**Comment by WolfgangSenff** [comment]
I'm closing this now since I haven't heard back and what you've done is clearly wrong. Please see the wiki for more.
