### ISSUE TITLE
[BUG] Firebase.Auth.auth.idtoken is empty

### ISSUE THREAD

**Issue by TrevorBlythe** [GodotNuts/GodotFirebase#414]
Im attempting to read and write to a real time database. I have authentication done with some other thing, other then Firebase. I tried to use this function
```
Firebase.Database.get_database_reference("https://s************.firebaseio.com/")
```
But got an error
```
Invalid get index 'idtoken' (on base: 'Dictionary').
database/reference.gd ~ line 124 at function _get_remaining _path
```

**To Reproduce**
Ubuntu, Godot 4.2.2, Install firebase and run the above line of code.

**Expected behavior**
Should return database reference.

**Environment:**
Ubuntu

**Comment by WolfgangSenff** [comment]
You have to be logged in at the moment - also, that's definitely not the path you want for the reference. It seems like you didn't read the wiki for any of the setup, nor how to use the RealtimeDatabase. Go ahead and check that out here to ensure you're authenticated, https://github.com/GodotNuts/GodotFirebase/wiki/Authentication-and-User-Management, and then here to see how to use the RTDB: https://github.com/GodotNuts/GodotFirebase/wiki/Realtime-Database#connecting. I'm going to go ahead and close this, since I'm certain these two things will fix all your issues.

**Comment by TrevorBlythe** [comment]
But I want the users to authenticate with facebook at runtime, but the only way to authenticate with this is with .env file

**Comment by TrevorBlythe** [comment]
I did anonymous login before the database thing and it still didnt work even with a fixed path same error

**Comment by WolfgangSenff** [comment]
You have to put the API key. It won't work without that.

**Comment by WolfgangSenff** [comment]
Stop wasting my time please. 🫤 You have to put all the info they gave you in your file into the .env. The API key is for all of Firebase, not the rtdb.

**Comment by TrevorBlythe** [comment]
![Screenshot from 2024-05-30 13-58-38](https://github.com/GodotNuts/GodotFirebase/assets/77030926/429eb020-1487-4d85-abea-9e47402dd003)
Its not giving me an api key anywhere in the project, I have nothing to host so im cant use firebase hosting, i think that has an api key but im only using rtdb and functions.

**Comment by TrevorBlythe** [comment]
![Screenshot from 2024-07-10 15-29-24](https://github.com/GodotNuts/GodotFirebase/assets/77030926/f4b11ec2-0422-4c56-9cbc-b19555bfea7c)
IGNORE THAT SCREENSHOT ABOVE WRONG IMAGE, this is the right one.

**Comment by WolfgangSenff** [comment]
Go into the project settings for your project and add the values you find in this section (note I had to click config at the top, although you don't have to technically) into the .env file.
![image](https://github.com/GodotNuts/GodotFirebase/assets/148612/e7d3b718-f2a6-487f-91ce-c436925efd89)

**Comment by TrevorBlythe** [comment]
I created a webapp and it gave me the values you were talking about, all the way up to "appID" (no measurementId). It shows the same error though, do I have to create it as an android app instead of a web app?

**Comment by WolfgangSenff** [comment]
No, you shouldn't. You put the apiKey in the right place, and so on, right? And you formatted them the way it is in the sample .env file, right?

**Comment by TrevorBlythe** [comment]
I did I copied from the example env and then pasted my keys in.

Its probably not working because im using the project from the "assetLib" section of Godot instead of the recommended installation. But that is the only one I could use because when I copied over the files from the github instead of downloading it from the assetLib, it says it cannot parse the class.

I looked in the scripts and some of the tool scripts just have the word "tool" at the top of the script, instead of the "@tool" and when I fix those it ends up on an error, "Cannot find PoolStringArray in scope"

Is this addon meant to be ran on 4.2.2?

**Comment by WolfgangSenff** [comment]
Yes, but if you downloaded it that way (from Github), then you accidentally downloaded the 3.x version, called Main. Remember, the plugin has to work on both 3.x and 4.x, and if you see tool with no at symbol, that's the wrong version for 4.x. It should work fine from the asset lib. How about I make a video to show how to set the whole thing up tomorrow, starting a series of videos on the plugin that I've been meaning to make for a while? I'll post a link here directly, as well as all over the place. :P

**Comment by WolfgangSenff** [comment]
If you want to get it from Github directly, you have to go here to get it: https://github.com/GodotNuts/GodotFirebase/tree/4.x. Also, due to a bug in Godot, after you get it and delete your previous version and add the above version into your codebase, make sure (while Godot is completely closed) that you delete your .godot folder in your entire project's folder. It will cause a lot of problems otherwise due to Godot's caching mechanism.

**Comment by TrevorBlythe** [comment]
A video tutorial series on the plugin sounds like a fantastic idea!  I've been watching old videos on it but they haven't really got me anywhere except here. I'm really just trying to use this so I can put multiplayer with the real time database. I'll be sure to check the link you post if you decide to do it.

**Comment by WolfgangSenff** [comment]
With multiplayer there, do you mean like actual moving characters around in "realtime" and stuff, or just turn-based? If the former, you unfortunately cannot do that with the realtime database. Aside from the cost (sending tons of updates will cost you a lot of money), it's just not anywhere near fast enough. They call it the realtime database, but that's deceptive - it is not very fast relative to actual multiplayer, like for instance the high-level multiplayer networking API. You really need a dedicated server for it.

**Comment by TrevorBlythe** [comment]
Wow that is kind of deceptive... :(. I did want real time multiplayer but I guess that was never going to work anyway. I wish they gave you a ballpark of how real-time it really was before letting you use it.

**Comment by WolfgangSenff** [comment]
Yeah. Honestly the name has always bothered me as it's deceptive. I'm sorry about that. I'm still working on the video, hopefully can get it out by the weekend.

**Comment by TrevorBlythe** [comment]
Im coming back to this and I wanted to check the latency of realtime database. And it seems to only be about 40 ms for me. which is pretty good actually. So maybe they improved it over time.

**Comment by WolfgangSenff** [comment]
Unfortunately not! They have no guarantees of speed. You got lucky, or live very near a server, is more likely. In addition, if you use it for even close to real-time updates, you're pretty much going bankrupt if your game gets really popular, or even a little bit.

**Comment by TrevorBlythe** [comment]
💀 Okay there goes my hopes and dreams

**Comment by TrevorBlythe** [comment]
did you ever get a video tutorial up

**Comment by WolfgangSenff** [comment]
No - I unfortunately lost my job, and have been trying to find small jobs. Videos for this stuff do not take precedence.
