### ISSUE TITLE
[FEATURE REQUEST] Warn to download the correct addon version

### ISSUE THREAD

**Issue by psychowolf960** [GodotNuts/GodotFirebase#433]
**Problem encountered**
When downloading the plugin it's easy to download the Godot 3 version and get a little stuck on the problem because it's not clearly marked to go for the godot 4 branch.

**A possible solution**
Add a simple line in the installation instructions of the wiki to warn the newcomers their choose the correct version.

**Alternative solution**
Make the godot 4 branch the main one. I don't exactly know how much people are still on Godot 3 and their reason but with the time passing it should logically be replace by godot 4.

**Additional context**
Downloading godot 3 version on godot 4 give the following error:
 `Unable to load addon script from path: 'res://addons/http-sse-client/httpsseclient_plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/http-sse-client/plugin.cfg' to prevent further errors.`

**Comment by WolfgangSenff** [comment]
Good idea, will add that! And will comment here when I've done so and close this.

**Comment by WolfgangSenff** [comment]
Okay, that was quick and easy. :P Put it right on the main page.
