### ISSUE TITLE
[BUG] Windows export asks for .env file and does not connect to firebase

### ISSUE THREAD

**Issue by rmlz** [GodotNuts/GodotFirebase#438]
**Describe the bug**
After exporting my game for a Windows preset, the game cannot connect to Firebase because the plugin is unable to locate the .env file.

**To Reproduce**

1. Export the game.
2. Run the console version.
3. GodotFirebase logs that it cannot find the .env file.

**Expected behavior**
The expected behavior is that the .env data would be embedded within the game's executable.

**Screenshots**
Not applicable.

**Environment:**

- Windows 11

**Additional context**
I haven't tried this yet, but I suspect adding a copy of the .env file to the Windows export directory might resolve the issue. However, I don’t believe it's safe to ship the game with a visible .env file, so I feel like I'm missing some configuration step prior to exporting.

Apologies if I'm reporting this to the wrong place, and thanks in advance for your assistance.

**Comment by WolfgangSenff** [comment]
You have to make sure *.env is in your files that get exported under resources.
