### ISSUE TITLE
New OAuth integration with google credentials - passwordUpdatedAt is not in the payload therefore raising exception error

### ISSUE THREAD

**Issue by tommasodargenio** [GodotNuts/GodotFirebase#67]
I'm testing the new OAuth integration (btw thanks a million to implementing this feature so quickly!!), I've got an error in the FirebaseUserData class (file: user_data.gd), the exception is raised for row 20 where the field passwordUpdatedAt is not in the payload returned by google during the authentication transaction. 

I've commented the row for now and it all worked fine after few other hiccups that got sorted automagically (if it happens again I'll open a new issue)

**Comment by fenix-hub** [comment]
#72 closes this.
