### ISSUE TITLE
FirstoreDocument cannot contain collections

### ISSUE THREAD

**Issue by WolfgangSenff** [GodotNuts/GodotFirebase#97]
While working with Firestore, I managed to create a Document in the console that contains a collection of other documents. This type is currently missing from the list and it would be very useful for our users. I'll work around it for now by adding the same document to the previous collection and find a better way to structure the initial collection name, but we'll need to implement it, since (apparently) this is a valid setup in Firestore.

**Comment by WolfgangSenff** [comment]
This is actually not an issue, as it turns out. Need to add a comment to the Wiki that you have to go to the collection even if it's nested by utilizing the entire path to whatever collection you want. If it's nested, you have to go through the nested structure directly the first time you call to create the FirestoreCollection - which is completely fine.

**Comment by DanielVZ96** [comment]
@WolfgangSenff I'm sorry but can you give some example on how you'd query nested collections?

**Comment by BearDooks** [comment]
@DanielVZ96 I am going to move this question over to the discussions section. I just saw that you had posted here, but I think it is better suited for there.
